### ISSUE TITLE
section2以降の見出しの数字がデザインと異なる

### ISSUE THREAD

**Issue by takahiro-nakayama** [satomi-ya/Training_2#3]
デザインでは数字の下にバーがあります。
<img width="190" alt="スクリーンショット 2019-07-01 21 40 00" src="https://user-images.githubusercontent.com/38599902/60437254-eda36e80-9c48-11e9-8a85-c666578fc63a.png">
<img width="272" alt="スクリーンショット 2019-07-01 21 40 16" src="https://user-images.githubusercontent.com/38599902/60437264-f431e600-9c48-11e9-9594-93b359d33897.png">

**Comment by satomi-ya** [comment]
忘れてました、すみません。。

そして、教えてください。
border-bottomでバーをつけるのかと思いきや、
紫の四角で囲んだ全体が見出しだから、四角のbottomについてしまいます。

text-decorationだと数字にくっついちゃうし、
どう記載するのが正解なんでしょうか？

**Comment by takahiro-nakayama** [comment]
cssの疑似要素で実装できます！

https://github.com/satomi-ya/Training_2/blob/93fdec423b2b77e87dd88a7c5dfa9a7ecd7528ad/scss/style.scss#L120-L132

```css
.No1 {
  width: 168px;
  height: 155px;
  background-color: #5e3db3;
  display: inline-block;
  position: absolute;
  top: 211px;
  left: 876px;
  display: flex;
  align-items: center;
  justify-content: center;
  p {
    color: #fff;
    text-align: center;
    display: flex;
    flex-direction: column;
    flex-wrap: wrap;
    align-items: center;
    line-height: 1.5;
    font-size: 24px;
    &:after {
      content: "";
      display: block;
      background: #fff;
      opacity: .3;
      width: 22px;
      height: 5px;
      border-radius: 2.5px;
    }
  }
}
```
